@startuml modelo

  class Area {
    - title: String
    - event: Event
  }

  class Event {
    - name: String
    - city: String
    - start: Date
    - end: Date
    - areas: List<Area>
  }

  Event "1, 1" *-- "1, n" Area 

  class User { 
    - name: String 
    - email: String
    - password: String
    - institution: String
    - areas: List<Area>
    - roles: List<Role>
  }

  User "0, n" --> "0, n" Area

  class Role {
    - title: String
  }

  User "0, n" *.. "1, n" Role

@enduml