@startuml states

  [*] --> Submitted : Usuário submete artigo
  Submitted --> UnderReview : Artigo é entregue aos revisores
  UnderReview --> Accepted : Artigo aceito pelos revisores
  UnderReview --> Rejected : Artigo rejeitado pelos revisores

  Accepted --> [*]
  Rejected --> [*]

@enduml