@startuml states

  [*] --> Submitted : Usuário submete artigo
  Submitted --> UnderReview : Artigo é entregue aos revisores
  UnderReview --> Accepted : 2 pareceres positivos
  UnderReview --> Rejected : 2 pareceres negativos
  UnderReview --> Attention : Pareceres conflitantes (de igual tamanho)
  Attention --> Accepted : Consenso por aceite
  Attention --> Rejected : Consenso por rejeição

  Accepted --> [*]
  Rejected --> [*]

@enduml
